Repository Ajou-Play/client, pull requests merged in 2022-11, with the labels that each got.

#42 [Feat] chat UI
  public/asset/ChatProfile.svg
  src/Component/ChannelInfoContainer/ChannelInfoContainer.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.type.ts
  src/Component/MessageCotent/ReceiverMessageContent/ReceiverMessageContent.tsx
  src/Component/MessageCotent/SenderMessageContent/SenderMessageContent.tsx
  src/Component/ProfileImage/ProfileImage.tsx
  src/Component/ProfileImage/index.ts
  src/Component/WindowContainer/MessageWindow/MessageWindow.tsx
  src/Component/WindowContainer/MessageWindow/MessageWindow.util.ts
  src/Component/index.ts
  src/Context/index.ts
  src/Context/teamContext.tsx
  src/Page/MainPage/MainPage.tsx
  src/Socket/Chat/registerChatSocketEvent.ts
  src/Util/index.ts
  src/Util/preloadImg.ts
Labels: feat

#43 [Feat] 모달창UI 구현
  index.html
  package-lock.json
  package.json
  public/asset/Add.svg
  public/asset/CancelOrange.svg
  public/asset/PencilFill.svg
  public/asset/Search.svg
  src/App.css
  src/Component/Button/Button.tsx
  src/Component/Button/index.tsx
  src/Component/CamChat/CamChat.tsx
  src/Component/CamChatContainer/CamChatContainer.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.tsx
  src/Component/MeetingController/MeetingController.tsx
  src/Component/Modal/AddChannelModal/AddChannelModal.tsx
  src/Component/Modal/AddTeamModal/AddTeamModal.tsx
  src/Component/Modal/ExitTeamModal/ExitTeamModal.tsx
  src/Component/Modal/SelectSharedDisplayModal/SelectSharedDisplayModal.tsx
  src/Component/Modal/SetChannelModal/SetChannelModal.tsx
  src/Component/Modal/SetChannelModal/SetChannelModal.type.ts
  src/Component/Modal/SetPersonalModal/SetPersonalModal.hook.ts
  src/Component/Modal/SetPersonalModal/SetPersonalModal.tsx
  src/Component/Modal/SetPersonalModal/SetPersonalModal.type.ts
  src/Component/Modal/SetPersonalModal/SetPersonalModal.util.ts
  src/Component/Modal/SetTeamModal/SetTeamModal.tsx
  src/Component/Modal/SetTeamModal/SetTeamModal.type.ts
  src/Component/Modal/index.ts
  src/Component/TeamCreateModal/TeamCreateModal.tsx
  src/Component/TeamInfoContainer/BasicTeamInfo/BasicTeamInfo.tsx
  src/Component/TeamInfoContainer/TeamInfoContainer.tsx
  src/Component/TeamList/TeamList.tsx
  src/Component/TeamList/TeamList.type.ts
  src/Component/index.ts
  src/Context/WebRTC/WebRTC.hook.tsx
  src/Hook/index.ts
  src/Hook/useModal.tsx
  src/Hook/useStep.tsx
  src/Page/MainPage/MainPage.hook.tsx
  src/Page/MainPage/MainPage.tsx
  src/Page/MainPage/MainPage.type.ts
  src/_msw/Team/handler.ts
  src/_msw/User/handler.ts
  src/portal.tsx
Labels: feat

#45 Feat/web rtc
  src/App.tsx
  src/Component/LoginForm/LoginForm.tsx
  src/Component/LoginForm/LoginForm.util.ts
  src/Component/MeetingContainer/MeetingContainer.tsx
  src/Component/MeetingController/MeetingController.tsx
  src/Component/MeetingController/MeetingController.type.ts
  src/Component/Modal/SetPersonalModal/SetPersonalModal.util.ts
  src/Component/RegisterForm/RegisterForm.tsx
  src/Component/RegisterForm/RegisterForm.type.ts
  src/Component/RegisterForm/RegisterForm.util.ts
  src/Component/WindowContainer/MessageWindow/MessageWindow.tsx
  src/Context/WebRTC/WebRTC.hook.tsx
  src/Context/WebRTC/WebRTC.provider.tsx
  src/Context/WebRTC/WebRTC.util.ts
  src/Page/MainPage/MainPage.tsx
  src/Page/MainPage/MainPage.util.ts
  src/Page/PrivatePage/PrivatePage.tsx
  src/Page/PrivatePage/PrivatePage.type.ts
  src/Page/PrivatePage/index.ts
  src/Page/index.ts
  src/Socket/WebRTC/webRTCInitSocket.ts
  src/Socket/WebRTC/webRTCReceiveEvent.ts
  src/Socket/WebRTC/webRTCSendEvent.ts
  src/Util/axios.ts
  src/Util/storage.ts
  src/main.tsx
Labels: enhancement, feat

#47 [Feat] 이전 채팅 기록 api 로직 추가
  src/Component/WindowContainer/MessageWindow/MessageWindow.hook.ts
  src/Component/WindowContainer/MessageWindow/MessageWindow.tsx
  src/Component/WindowContainer/MessageWindow/MessageWindow.type.ts
  src/Component/WindowContainer/MessageWindow/MessageWindow.util.ts
  src/_msw/Chat/handler.ts
  src/_msw/Chat/index.ts
Labels: feat

#48 [Enhance] router분리
  src/App.tsx
  src/Component/ChannelInfoContainer/Archive/ChannelArchive.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.type.ts
  src/Component/ChannelInfoContainer/MainView/MainView.tsx
  src/Component/ChannelInfoContainer/MainView/MainView.type.ts
  src/Page/MainPage/MainPage.hook.tsx
  src/Page/MainPage/MainPage.tsx
  src/Page/MainPage/MainPage.type.ts
Labels: enhancement
