Repository Ajou-Play/client, pull requests merged in 2022-10, with the labels that each got.

#15 feat: msw template init
  src/_msw/Channel/handler.ts
  src/_msw/Channel/index.ts
  src/_msw/Docs/handler.ts
  src/_msw/Docs/index.ts
  src/_msw/Team/handler.ts
  src/_msw/Team/index.ts
  src/_msw/User/handler.ts
  src/_msw/User/index.ts
  src/_msw/index.ts
  src/_msw/index.tsx
  src/_msw/type.ts
Labels: feat

#17 feat: tailwind init
  index.html
  package-lock.json
  package.json
  src/input.css
  tailwind.config.cjs
Labels: install

#20 feat: loginPage UI
  package-lock.json
  package.json
  src/Component/LoginForm/LoginForm.style.ts
  src/Component/LoginForm/LoginForm.tsx
  src/Component/LoginForm/LoginForm.type.ts
  src/Component/LoginForm/index.ts
  src/Component/LoginInput/LoginInput.style.ts
  src/Component/LoginInput/LoginInput.tsx
  src/Component/LoginInput/LoginInput.type.ts
  src/Component/LoginInput/index.ts
  src/Component/index.ts
  src/Page/LoginPage/LoginPage.style.ts
  src/Page/LoginPage/LoginPage.tsx
Labels: feat

#24 Feat/window in main
  public/asset/Cancel.svg
  public/asset/Cursor.svg
  public/asset/Member.svg
  public/asset/Message.svg
  src/Component/ChannelInfoContainer/ChannelInfoContainer.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.type.ts
  src/Component/MessageCotent/MessageContent.tsx
  src/Component/MessageCotent/MessageContent.util.ts
  src/Component/MessageCotent/ReceiverMessageContent/ReceiverMessageContent.tsx
  src/Component/MessageCotent/ReceiverMessageContent/index.ts
  src/Component/MessageCotent/SenderMessageContent/SenderMessageContent.tsx
  src/Component/MessageCotent/SenderMessageContent/index.ts
  src/Component/MessageCotent/index.ts
  src/Component/TeamInfoContainer/TeamInfoContainer.tsx
  src/Component/TeamList/TeamList.tsx
  src/Component/WindowContainer/MemberIcon/MemberIcon.tsx
  src/Component/WindowContainer/MemberIcon/index.ts
  src/Component/WindowContainer/MessageWindow/MessageWindow.tsx
  src/Component/WindowContainer/MessageWindow/index.ts
  src/Component/WindowContainer/TeamMemberWindow/TeamMemberWindow.tsx
  src/Component/WindowContainer/TeamMemberWindow/index.ts
  src/Component/WindowContainer/WindowContainer.tsx
  src/Component/WindowContainer/index.ts
  src/Component/WindowContainer/windowContainer.type.ts
  src/Component/index.ts
  src/Hook/index.ts
  src/Hook/useMultiSelection.tsx
  src/Page/MainPage/MainPage.hook.tsx
  src/Page/MainPage/MainPage.tsx
  src/Page/MainPage/MainPage.util.ts
  src/_msw/Team/handler.ts
  src/_msw/Team/index.ts
  tailwind.config.cjs
Labels: feat

#27 Feat/init socket
  package-lock.json
  package.json
  src/Socket/Archive/index.ts
  src/Socket/Chat/index.ts
  src/Socket/Chat/joinChatRoom.ts
  src/Socket/Chat/leaveChatRoom.ts
  src/Socket/Chat/sendMessage.ts
  src/Socket/WebRTC/index.ts
  src/Socket/emitEvent.ts
  src/Socket/index.ts
  src/Socket/initSocket.ts
  src/Socket/registerSocketEvent.ts
  src/Socket/socket.ts
Labels: feat

#29 Feat/test#1
  .gitignore
  package-lock.json
  package.json
  src/Component/ChannelInfoContainer/ChannelInfoContainer.test.ts
  src/Component/ChannelInfoContainer/ChannelInfoContainer.util.ts
  src/Component/MessageCotent/MessageContent.test.ts
  src/Component/TeamInfoContainer/BasicTeamInfo/BasicTeamInfo.test.ts
  src/Component/TeamInfoContainer/BasicTeamInfo/BasicTeamInfo.util.ts
  src/Page/MainPage/MainPage.test.ts
  src/Page/MainPage/MainPage.util.ts
  src/_msw/Archive/handler.ts
  src/_msw/Channel/handler.ts
  src/_msw/Team/handler.ts
  src/sum.test.js
Labels: feat, discussion

#28 Feat/main page
  public/asset/ArchiveIcon.svg
  public/asset/docxIcon.svg
  public/asset/mettingOff.svg
  public/asset/mettingOn.svg
  public/asset/micOff.svg
  public/asset/micOn.svg
  public/asset/pptIcon.svg
  public/asset/windowOff.svg
  public/asset/windowOn.svg
  src/Component/ChannelInfoContainer/Archive/ChannelArchive.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.tsx
  src/Component/ChannelInfoContainer/ChannelInfoContainer.type.ts
  src/Component/ChannelInfoContainer/Home/Calendar/Calendar.tsx
  src/Component/ChannelInfoContainer/Home/Calendar/index.ts
  src/Component/ChannelInfoContainer/Home/ChannelHome.hook.tsx
  src/Component/ChannelInfoContainer/Home/ChannelHome.tsx
  src/Component/ChannelInfoContainer/Home/ChannelHome.util.ts
  src/Component/ChannelInfoContainer/Home/CharacterInfo/CharacterInfo.tsx
  src/Component/ChannelInfoContainer/Home/CharacterInfo/index.ts
  src/Component/ChannelInfoContainer/Home/SmallArchiveList/ChannelHome.const.ts
  src/Component/ChannelInfoContainer/Home/SmallArchiveList/SmallArchiveList.const.ts
  src/Component/ChannelInfoContainer/Home/SmallArchiveList/SmallArchiveList.tsx
  src/Component/ChannelInfoContainer/Home/SmallArchiveList/SmallArchiveList.type.ts
  src/Component/ChannelInfoContainer/Home/SmallArchiveList/index.ts
  src/Component/MeetingController/MeetingController.const.ts
  src/Component/MeetingController/MeetingController.tsx
  src/Component/MeetingController/MeetingController.type.ts
  src/Component/MeetingController/index.ts
  src/Component/TeamInfoContainer/BasicTeamInfo/BasicTeamInfo.tsx
  src/Component/TeamInfoContainer/TeamInfoContainer.tsx
  src/Component/WindowContainer/MessageWindow/MessageWindow.tsx
  src/Page/MainPage/MainPage.hook.tsx
  src/Page/MainPage/MainPage.tsx
  src/Page/MainPage/MainPage.type.ts
Labels: feat, discussion

#34 Enhance/init socket
  package-lock.json
  package.json
  src/Socket/Chat/chatInitSocket.ts
  src/Socket/Chat/index.ts
  src/Socket/Chat/joinChatRoom.ts
  src/Socket/Chat/leaveChatRoom.ts
  src/Socket/Chat/registerChatSocketEvent.ts
  src/Socket/Chat/sendMessage.ts
  src/Socket/emitEvent.ts
  src/Socket/index.ts
  src/Socket/initSocket.ts
  src/Socket/registerSocketEvent.ts
  src/Socket/socket.ts
Labels: enhancement, feat

#39 [Refactor] meeting controller logic
  package-lock.json
  package.json
  src/App.css
  src/Component/MeetingController/MeetingController.tsx
Labels: refactor

#38 Feat/calendar
  .eslintrc.json
  public/asset/Calendar/nextMonth.svg
  public/asset/Calendar/prevMonth.svg
  src/Component/ChannelInfoContainer/Archive/ChannelArchive.tsx
  src/Component/ChannelInfoContainer/Archive/ChannelArchive.type.ts
  src/Component/ChannelInfoContainer/Home/Calendar/Calendar.const.ts
  src/Component/ChannelInfoContainer/Home/Calendar/Calendar.hook.tsx
  src/Component/ChannelInfoContainer/Home/Calendar/Calendar.tsx
  src/Component/ChannelInfoContainer/Home/Calendar/Calendar.type.ts
  src/Component/ChannelInfoContainer/Home/Calendar/Calendar.util.ts
  src/Component/ChannelInfoContainer/Home/Calendar/CellOfCalendar/CellOfCalendar.const.ts
  src/Component/ChannelInfoContainer/Home/Calendar/CellOfCalendar/CellOfCalendar.tsx
  src/Component/ChannelInfoContainer/Home/Calendar/CellOfCalendar/CellOfCalendar.type.ts
  src/Component/ChannelInfoContainer/Home/Calendar/CellOfCalendar/index.ts
  src/Component/ChannelInfoContainer/Home/ChannelHome.const.ts
  src/Component/ChannelInfoContainer/Home/ChannelHome.hook.tsx
  src/Component/ChannelInfoContainer/Home/ChannelHome.tsx
  src/Component/ChannelInfoContainer/Home/ChannelHome.type.ts
  src/Component/ChannelInfoContainer/Home/ChannelHome.util.ts
  src/Component/ChannelInfoContainer/Home/SmallArchiveList/SmallArchiveList.tsx
  src/Page/MainPage/MainPage.hook.tsx
  src/Util/getElementData.ts
  src/Util/index.ts
  src/_msw/Archive/handler.ts
Labels: feat

#40 [Feat] registerPage add validate
  public/asset/Lock.svg
  public/asset/Person.svg
  src/Component/LoginForm/LoginForm.style.ts
  src/Component/LoginForm/LoginForm.tsx
  src/Component/LoginForm/LoginForm.type.ts
  src/Component/LoginInput/LoginInput.style.ts
  src/Component/LoginInput/LoginInput.tsx
  src/Component/LoginInput/LoginInput.type.ts
  src/Component/RegisterForm/RegisterForm.style.ts
  src/Component/RegisterForm/RegisterForm.tsx
  src/Component/RegisterForm/RegisterForm.type.ts
  src/Component/RegisterForm/index.ts
  src/Component/index.ts
  src/Hook/useMovePage.tsx
  src/Page/LoginPage/LoginPage.tsx
  src/Page/RegisterPage/RegisterPage.style.ts
  src/Page/RegisterPage/RegisterPage.tsx
Labels: feat
